// Package openapi contains the documented discord-bot HTTP contract.
package openapi

// Spec is the OpenAPI 3.0 document served by the HTTP API.
const Spec = `{
  "openapi":"3.0.3",
  "info":{"title":"discord-bot API","description":"Single-guild Discord Components V2, settings, and verification guard API.","version":"1.0.0"},
  "paths":{
    "/status":{"get":{"tags":["Public"],"summary":"Read dependency status","responses":{"200":{"description":"Service status"}}}},
    "/guild/members":{"get":{"tags":["Public"],"summary":"Read approximate guild member and presence counts","responses":{"200":{"description":"Guild statistics"},"503":{"description":"Guild statistics unavailable"}}}},
    "/api/messages":{"post":{"tags":["Messages"],"summary":"Create a managed Components V2 message","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/MessageDefinition"}}}},"responses":{"201":{"description":"Created"},"400":{"$ref":"#/components/responses/BadRequest"},"409":{"$ref":"#/components/responses/Conflict"}}},"get":{"tags":["Messages"],"summary":"List managed messages","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Message page"}}}},
    "/api/messages/{key}":{"parameters":[{"$ref":"#/components/parameters/MessageKey"}],"get":{"tags":["Messages"],"summary":"Read a managed message","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Message"},"404":{"$ref":"#/components/responses/NotFound"}}},"put":{"tags":["Messages"],"summary":"Replace Components V2 desired state","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/MessageDefinition"}}}},"responses":{"200":{"description":"Updated"},"409":{"$ref":"#/components/responses/Conflict"}}},"delete":{"tags":["Messages"],"summary":"Archive a managed message","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"responses":{"200":{"description":"Archived"}}}},
    "/api/messages/{key}/assignment":{"put":{"tags":["Messages"],"summary":"Assign a message to a channel in the configured guild","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/MessageKey"},{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"responses":{"200":{"description":"Assigned"}}}},
    "/api/messages/{key}/reconcile":{"post":{"tags":["Messages"],"summary":"Schedule message reconciliation","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/MessageKey"}],"responses":{"202":{"description":"Scheduled"}}}},
    "/api/settings":{"get":{"tags":["Settings"],"summary":"List effective dotted settings","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Settings"}}}},
    "/api/settings/{key}":{"parameters":[{"$ref":"#/components/parameters/SettingKey"}],"get":{"tags":["Settings"],"summary":"Read an effective setting","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Setting"}}},"put":{"tags":["Settings"],"summary":"Set a typed setting override","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/OptionalIfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["value"],"properties":{"value":{}}}}}},"responses":{"200":{"description":"Set"},"409":{"$ref":"#/components/responses/Conflict"}}},"delete":{"tags":["Settings"],"summary":"Reset a setting to its code default","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/OptionalIfMatch"}],"responses":{"200":{"description":"Reset"}}}},
    "/api/verification/groups":{"get":{"tags":["Verification"],"summary":"List verification groups","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Groups"}}},"post":{"tags":["Verification"],"summary":"Create one of at most five groups","security":[{"BearerAuth":[]}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/VerificationGroup"}}}},"responses":{"201":{"description":"Created"},"400":{"$ref":"#/components/responses/BadRequest"}}}},
    "/api/verification/groups/{id}":{"parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"string","format":"uuid"}}],"get":{"tags":["Verification"],"summary":"Read a group","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Group"}}},"put":{"tags":["Verification"],"summary":"Replace a group","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/VerificationGroup"}}}},"responses":{"200":{"description":"Updated"}}},"delete":{"tags":["Verification"],"summary":"Delete an unused group","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IfMatch"}],"responses":{"204":{"description":"Deleted"}}}},
    "/api/verification/memberships":{"get":{"tags":["Verification"],"summary":"List timestamped active memberships","security":[{"BearerAuth":[]}],"parameters":[{"name":"userId","in":"query","schema":{"type":"string"}}],"responses":{"200":{"description":"Memberships"}}}},
    "/api/verification/reconcile":{"post":{"tags":["Verification"],"summary":"Repair memberships, roles, markup, permissions, and anti-bot trap","security":[{"BearerAuth":[]}],"responses":{"202":{"description":"Reconciled"}}}}
  },
  "components":{
    "securitySchemes":{"BearerAuth":{"type":"http","scheme":"bearer"}},
    "parameters":{
      "MessageKey":{"name":"key","in":"path","required":true,"schema":{"type":"string","pattern":"^[a-z0-9][a-z0-9_-]{0,63}$"}},
      "SettingKey":{"name":"key","in":"path","required":true,"schema":{"type":"string","pattern":"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$"}},
      "IdempotencyKey":{"name":"Idempotency-Key","in":"header","required":true,"schema":{"type":"string","maxLength":128}},
      "IfMatch":{"name":"If-Match","in":"header","required":true,"schema":{"type":"integer","minimum":1}},
      "OptionalIfMatch":{"name":"If-Match","in":"header","required":false,"schema":{"type":"integer","minimum":1}}
    },
    "responses":{"BadRequest":{"description":"Invalid Discord-facing configuration"},"NotFound":{"description":"Unknown record"},"Conflict":{"description":"Duplicate or stale revision"}},
    "schemas":{
      "AllowedMentions":{"type":"object","required":["parse"],"properties":{"parse":{"type":"array","items":{"type":"string","enum":["everyone","roles","users"]}},"roles":{"type":"array","maxItems":100,"items":{"type":"string"}},"users":{"type":"array","maxItems":100,"items":{"type":"string"}},"repliedUser":{"type":"boolean"}}},
      "V2Component":{"type":"object","description":"Discord Components V2 object. Top-level types: Action Row (1), Section (9), Text Display (10), Media Gallery (12), File (13), Separator (14), Container (17). Maximum 40 total components; action rows contain at most five buttons."},
      "V2Payload":{"type":"object","required":["components","allowedMentions"],"properties":{"components":{"type":"array","minItems":1,"items":{"$ref":"#/components/schemas/V2Component"}},"allowedMentions":{"$ref":"#/components/schemas/AllowedMentions"}}},
      "MessageDefinition":{"type":"object","required":["key","guildId","channelId","payload"],"properties":{"key":{"type":"string"},"guildId":{"type":"string","description":"Must equal DISCORD_BOT_GUILD_ID."},"channelId":{"type":"string"},"payload":{"$ref":"#/components/schemas/V2Payload"}}},
      "VerificationGroup":{"type":"object","required":["key","roleId","buttonLabel","buttonStyle","position","enabled"],"properties":{"key":{"type":"string","maxLength":32},"roleId":{"type":"string"},"buttonLabel":{"type":"string","maxLength":80},"buttonEmoji":{"type":"string","maxLength":32},"buttonStyle":{"type":"integer","minimum":1,"maximum":4},"position":{"type":"integer","minimum":1,"maximum":5},"enabled":{"type":"boolean"}}}
    }
  }
}`
