// Package openapi contains the documented discord-bot HTTP contract.
package openapi

// Spec is the OpenAPI 3.0 document served by the HTTP API.
const Spec = `{
  "openapi":"3.0.3",
  "info":{"title":"discord-bot API","description":"Single-guild Discord operations and reusable Discord identity-link API.","version":"1.1.1"},
  "paths":{
    "/status":{"get":{"tags":["Public"],"summary":"Read dependency status","responses":{"200":{"description":"Service status"}}}},
    "/guild/members":{"get":{"tags":["Public"],"summary":"Read approximate guild member and presence counts","responses":{"200":{"description":"Guild statistics"},"503":{"description":"Guild statistics unavailable"}}}},
    "/oauth/discord/start/{intentId}":{"get":{"tags":["Discord links"],"summary":"Start one browser OAuth attempt","description":"Public one-time browser route. The intent itself is created through the API-key-protected API.","parameters":[{"name":"intentId","in":"path","required":true,"schema":{"type":"string","format":"uuid"}}],"responses":{"302":{"description":"Redirect to Discord authorization"},"404":{"$ref":"#/components/responses/NotFound"},"409":{"$ref":"#/components/responses/Conflict"},"410":{"$ref":"#/components/responses/Gone"},"503":{"description":"Discord linking is disabled"}}}},
    "/oauth/discord/callback":{"get":{"tags":["Discord links"],"summary":"Receive Discord's OAuth callback","description":"Public callback registered in the Discord Developer Portal. It redirects only to a configured completion destination.","parameters":[{"name":"state","in":"query","required":true,"schema":{"type":"string"}},{"name":"code","in":"query","schema":{"type":"string"}},{"name":"error","in":"query","schema":{"type":"string"}}],"responses":{"303":{"description":"Redirect to the allowlisted completion URL with a one-time result code"},"400":{"$ref":"#/components/responses/BadRequest"},"404":{"$ref":"#/components/responses/NotFound"},"410":{"$ref":"#/components/responses/Gone"}}}},
    "/api/discord-links/intents":{"post":{"tags":["Discord links"],"summary":"Create an idempotent Discord link attempt","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLinkIntentRequest"}}}},"responses":{"201":{"description":"Created or replayed intent","content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLinkIntent"}}}},"400":{"$ref":"#/components/responses/BadRequest"},"401":{"$ref":"#/components/responses/Unauthorized"},"409":{"$ref":"#/components/responses/Conflict"},"503":{"description":"Discord linking is disabled"}}}},
    "/api/discord-links/login-intents":{"post":{"tags":["Discord links"],"summary":"Create an idempotent subject-free Discord login attempt","description":"After OAuth the result resolves to a subject only when the Discord user already has an active link.","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLoginIntentRequest"}}}},"responses":{"201":{"description":"Created or replayed login intent","content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLinkIntent"}}}},"400":{"$ref":"#/components/responses/BadRequest"},"401":{"$ref":"#/components/responses/Unauthorized"},"409":{"$ref":"#/components/responses/Conflict"},"503":{"description":"Discord OAuth is disabled"}}}},
    "/api/discord-links/results/exchange":{"post":{"tags":["Discord links"],"summary":"Exchange a short-lived OAuth result code","description":"The same Idempotency-Key may safely replay the result; a different key cannot consume it again.","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["code"],"properties":{"code":{"type":"string"}}}}}},"responses":{"200":{"description":"Link outcome","content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLinkResult"}}}},"400":{"$ref":"#/components/responses/BadRequest"},"401":{"$ref":"#/components/responses/Unauthorized"},"404":{"$ref":"#/components/responses/NotFound"},"410":{"$ref":"#/components/responses/Gone"}}}},
    "/api/discord-links/subjects/{subject}":{"parameters":[{"$ref":"#/components/parameters/LinkSubject"}],"get":{"tags":["Discord links"],"summary":"Read the latest link history by local subject","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Latest link","content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLink"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"404":{"$ref":"#/components/responses/NotFound"}}},"delete":{"tags":["Discord links"],"summary":"Idempotently unlink a local subject","description":"Uses the stable subject as its natural idempotency key and retains history.","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Unlinked history","content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLink"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"404":{"$ref":"#/components/responses/NotFound"}}}},
    "/api/discord-links/users/{discordUserId}":{"get":{"tags":["Discord links"],"summary":"Read the active link by Discord user ID","security":[{"BearerAuth":[]}],"parameters":[{"name":"discordUserId","in":"path","required":true,"schema":{"type":"string","pattern":"^[0-9]{1,20}$"}}],"responses":{"200":{"description":"Active link","content":{"application/json":{"schema":{"$ref":"#/components/schemas/DiscordLink"}}}},"401":{"$ref":"#/components/responses/Unauthorized"},"404":{"$ref":"#/components/responses/NotFound"}}}},
    "/api/messages":{"post":{"tags":["Messages"],"summary":"Create a managed Components V2 message","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/MessageDefinition"}}}},"responses":{"201":{"description":"Created"},"400":{"$ref":"#/components/responses/BadRequest"},"409":{"$ref":"#/components/responses/Conflict"}}},"get":{"tags":["Messages"],"summary":"List managed messages","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Message page"}}}},
    "/api/messages/{key}":{"parameters":[{"$ref":"#/components/parameters/MessageKey"}],"get":{"tags":["Messages"],"summary":"Read a managed message","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Message"},"404":{"$ref":"#/components/responses/NotFound"}}},"put":{"tags":["Messages"],"summary":"Replace Components V2 desired state","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/MessageDefinition"}}}},"responses":{"200":{"description":"Updated"},"409":{"$ref":"#/components/responses/Conflict"}}},"delete":{"tags":["Messages"],"summary":"Archive a managed message","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"responses":{"200":{"description":"Archived"}}}},
    "/api/messages/{key}/assignment":{"put":{"tags":["Messages"],"summary":"Assign a message to a channel in the configured guild","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/MessageKey"},{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"responses":{"200":{"description":"Assigned"}}}},
    "/api/messages/{key}/reconcile":{"post":{"tags":["Messages"],"summary":"Schedule message reconciliation","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/MessageKey"}],"responses":{"202":{"description":"Scheduled"}}}},
    "/api/settings":{"get":{"tags":["Settings"],"summary":"List effective dotted settings","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Settings"}}}},
    "/api/settings/{key}":{"parameters":[{"$ref":"#/components/parameters/SettingKey"}],"get":{"tags":["Settings"],"summary":"Read an effective setting","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Setting"}}},"put":{"tags":["Settings"],"summary":"Set a typed setting override","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/OptionalIfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["value"],"properties":{"value":{}}}}}},"responses":{"200":{"description":"Set"},"409":{"$ref":"#/components/responses/Conflict"}}},"delete":{"tags":["Settings"],"summary":"Reset a setting to its code default","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/OptionalIfMatch"}],"responses":{"200":{"description":"Reset"}}}},
    "/api/verification/groups":{"get":{"tags":["Verification"],"summary":"List verification groups","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Groups"}}},"post":{"tags":["Verification"],"summary":"Create one of at most five groups","security":[{"BearerAuth":[]}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/VerificationGroup"}}}},"responses":{"201":{"description":"Created"},"400":{"$ref":"#/components/responses/BadRequest"}}}},
    "/api/verification/groups/{id}":{"parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"string","format":"uuid"}}],"get":{"tags":["Verification"],"summary":"Read a group","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Group"}}},"put":{"tags":["Verification"],"summary":"Replace a group","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/VerificationGroup"}}}},"responses":{"200":{"description":"Updated"}}},"delete":{"tags":["Verification"],"summary":"Delete an unused group","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IfMatch"}],"responses":{"204":{"description":"Deleted"}}}},
    "/api/verification/memberships":{"get":{"tags":["Verification"],"summary":"List timestamped active memberships","security":[{"BearerAuth":[]}],"parameters":[{"name":"userId","in":"query","schema":{"type":"string"}}],"responses":{"200":{"description":"Memberships"}}}},
    "/api/verification/reconcile":{"post":{"tags":["Verification"],"summary":"Repair memberships, roles, markup, permissions, and anti-bot trap","security":[{"BearerAuth":[]}],"responses":{"202":{"description":"Reconciled"}}}}
  },
  "components":{
    "securitySchemes":{"BearerAuth":{"type":"http","scheme":"bearer"}},
    "parameters":{
      "MessageKey":{"name":"key","in":"path","required":true,"schema":{"type":"string","pattern":"^[a-z0-9][a-z0-9_-]{0,63}$"}},
      "SettingKey":{"name":"key","in":"path","required":true,"schema":{"type":"string","pattern":"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$"}},
      "IdempotencyKey":{"name":"Idempotency-Key","in":"header","required":true,"schema":{"type":"string","maxLength":128}},
      "IfMatch":{"name":"If-Match","in":"header","required":true,"schema":{"type":"integer","minimum":1}},
      "OptionalIfMatch":{"name":"If-Match","in":"header","required":false,"schema":{"type":"integer","minimum":1}}
      ,"LinkSubject":{"name":"subject","in":"path","required":true,"description":"Caller-owned stable identifier, URL encoded when needed.","schema":{"type":"string","pattern":"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$"}}
    },
    "responses":{"BadRequest":{"description":"Invalid request"},"Unauthorized":{"description":"Missing or invalid API key"},"NotFound":{"description":"Unknown record"},"Conflict":{"description":"Duplicate, occupied, or stale record"},"Gone":{"description":"Expired or previously consumed artifact"}},
    "schemas":{
      "AllowedMentions":{"type":"object","required":["parse"],"properties":{"parse":{"type":"array","items":{"type":"string","enum":["everyone","roles","users"]}},"roles":{"type":"array","maxItems":100,"items":{"type":"string"}},"users":{"type":"array","maxItems":100,"items":{"type":"string"}},"repliedUser":{"type":"boolean"}}},
      "V2Component":{"type":"object","description":"Discord Components V2 object. Top-level types: Action Row (1), Section (9), Text Display (10), Media Gallery (12), File (13), Separator (14), Container (17). Maximum 40 total components; action rows contain at most five buttons."},
      "V2Payload":{"type":"object","required":["components","allowedMentions"],"properties":{"components":{"type":"array","minItems":1,"items":{"$ref":"#/components/schemas/V2Component"}},"allowedMentions":{"$ref":"#/components/schemas/AllowedMentions"}}},
      "MessageDefinition":{"type":"object","required":["key","guildId","channelId","payload"],"properties":{"key":{"type":"string"},"guildId":{"type":"string","description":"Must equal DISCORD_BOT_GUILD_ID."},"channelId":{"type":"string"},"payload":{"$ref":"#/components/schemas/V2Payload"}}},
      "VerificationGroup":{"type":"object","required":["key","roleId","buttonLabel","buttonStyle","position","enabled"],"properties":{"key":{"type":"string","maxLength":32},"roleId":{"type":"string"},"buttonLabel":{"type":"string","maxLength":80},"buttonEmoji":{"type":"string","maxLength":32},"buttonStyle":{"type":"integer","minimum":1,"maximum":4},"position":{"type":"integer","minimum":1,"maximum":5},"enabled":{"type":"boolean"}}},
      "DiscordLinkIntentRequest":{"type":"object","required":["subject","completionKey"],"properties":{"subject":{"type":"string","pattern":"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$","description":"Stable identifier assigned by the caller, for example user:test-001."},"completionKey":{"type":"string","pattern":"^[a-z0-9][a-z0-9_-]{0,63}$","description":"Key registered in DISCORD_BOT_OAUTH_COMPLETION_URLS."}}},
      "DiscordLoginIntentRequest":{"type":"object","required":["completionKey"],"properties":{"completionKey":{"type":"string","pattern":"^[a-z0-9][a-z0-9_-]{0,63}$","description":"Key registered in DISCORD_BOT_OAUTH_COMPLETION_URLS."}}},
      "DiscordLinkIntent":{"type":"object","required":["intentId","kind","completionKey","status","expiresAt","createdAt","startUrl"],"properties":{"intentId":{"type":"string","format":"uuid"},"kind":{"type":"string","enum":["link","login"]},"subject":{"type":"string"},"completionKey":{"type":"string"},"status":{"type":"string","enum":["pending","started","processing","completed"]},"expiresAt":{"type":"string","format":"date-time"},"createdAt":{"type":"string","format":"date-time"},"startUrl":{"type":"string","format":"uri"}}},
      "DiscordLink":{"type":"object","required":["id","subject","discordUserId","username","scopes","status","linkedAt","createdAt","updatedAt"],"properties":{"id":{"type":"string","format":"uuid"},"subject":{"type":"string"},"discordUserId":{"type":"string"},"username":{"type":"string"},"globalName":{"type":"string"},"avatarHash":{"type":"string"},"avatarUrl":{"type":"string","format":"uri"},"scopes":{"type":"array","items":{"type":"string"}},"status":{"type":"string","enum":["linked","unlinked"]},"linkedAt":{"type":"string","format":"date-time"},"unlinkedAt":{"type":"string","format":"date-time"},"createdAt":{"type":"string","format":"date-time"},"updatedAt":{"type":"string","format":"date-time"}}},
      "DiscordLinkResult":{"type":"object","required":["status"],"properties":{"status":{"type":"string","enum":["linked","authenticated","not_linked","denied","conflict","failed"]},"subject":{"type":"string"},"errorCode":{"type":"string","enum":["authorization_denied","authorization_failed","provider_exchange_failed","identity_unavailable","subject_already_linked","discord_user_already_linked","discord_user_not_linked"]},"link":{"$ref":"#/components/schemas/DiscordLink"}}}
    }
  }
}`
