// Package openapi provides the public API contract.
package openapi

// Spec contains the OpenAPI document served in development.
const Spec = `{
  "openapi":"3.0.3",
  "info":{"title":"discord-bot API","description":"Idempotent managed Discord messages and configurable agreement companies.","version":"2.0.0"},
  "paths":{
    "/status":{"get":{"tags":["Public"],"summary":"Read dependency status","responses":{"200":{"description":"Service status"}}}},
    "/api/messages":{"post":{"tags":["Messages"],"summary":"Create a managed Components V2 message","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/MessageDefinition"}}}},"responses":{"201":{"description":"Created"},"400":{"$ref":"#/components/responses/BadRequest"},"409":{"$ref":"#/components/responses/Conflict"}}},"get":{"tags":["Messages"],"summary":"List managed messages","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Message page"}}}},
    "/api/messages/{key}":{"parameters":[{"$ref":"#/components/parameters/MessageKey"}],"get":{"tags":["Messages"],"summary":"Read a managed message","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Message"},"404":{"$ref":"#/components/responses/NotFound"}}},"put":{"tags":["Messages"],"summary":"Replace Components V2 desired state","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/MessageDefinition"}}}},"responses":{"200":{"description":"Updated"},"409":{"$ref":"#/components/responses/Conflict"}}},"delete":{"tags":["Messages"],"summary":"Archive a managed message","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"responses":{"200":{"description":"Archived"}}}},
    "/api/messages/{key}/assignment":{"put":{"tags":["Messages"],"summary":"Assign a message to a channel in the configured guild","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/MessageKey"},{"$ref":"#/components/parameters/IdempotencyKey"},{"$ref":"#/components/parameters/IfMatch"}],"responses":{"200":{"description":"Assigned"}}}},
    "/api/messages/{key}/reconcile":{"post":{"tags":["Messages"],"summary":"Schedule message reconciliation","security":[{"BearerAuth":[]}],"parameters":[{"$ref":"#/components/parameters/MessageKey"}],"responses":{"202":{"description":"Scheduled"}}}},
    "/api/companies":{"get":{"tags":["Companies"],"summary":"List companies","security":[{"BearerAuth":[]}],"responses":{"200":{"description":"Company list"},"401":{"description":"Unauthorized"}}},"post":{"tags":["Companies"],"summary":"Create a company","security":[{"BearerAuth":[]}],"responses":{"201":{"description":"Company created"},"400":{"description":"Invalid company"},"401":{"description":"Unauthorized"},"409":{"description":"Duplicate identifier"}},"requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Company"}}}}}},
    "/api/companies/{id}":{"delete":{"tags":["Companies"],"summary":"Delete an empty company","security":[{"BearerAuth":[]}],"responses":{"204":{"description":"Deleted"},"401":{"description":"Unauthorized"},"404":{"description":"Company not found"},"409":{"description":"Company has agreements"}},"parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"string"}}]}}
  },
  "components":{"securitySchemes":{"BearerAuth":{"type":"http","scheme":"bearer"}},"parameters":{"MessageKey":{"name":"key","in":"path","required":true,"schema":{"type":"string","pattern":"^[a-z0-9][a-z0-9_-]{0,63}$"}},"IdempotencyKey":{"name":"Idempotency-Key","in":"header","required":true,"schema":{"type":"string","maxLength":128}},"IfMatch":{"name":"If-Match","in":"header","required":true,"schema":{"type":"integer","minimum":1}}},"responses":{"BadRequest":{"description":"Invalid request"},"Unauthorized":{"description":"Missing or invalid API key"},"NotFound":{"description":"Unknown record"},"Conflict":{"description":"Duplicate or stale record"}},"schemas":{"AllowedMentions":{"type":"object","required":["parse"],"properties":{"parse":{"type":"array","items":{"type":"string","enum":["everyone","roles","users"]}},"roles":{"type":"array","maxItems":100,"items":{"type":"string"}},"users":{"type":"array","maxItems":100,"items":{"type":"string"}},"repliedUser":{"type":"boolean"}}},"V2Component":{"type":"object","description":"Discord Components V2 object."},"V2Payload":{"type":"object","required":["components","allowedMentions"],"properties":{"components":{"type":"array","minItems":1,"items":{"$ref":"#/components/schemas/V2Component"}},"allowedMentions":{"$ref":"#/components/schemas/AllowedMentions"}}},"MessageDefinition":{"type":"object","required":["key","guildId","channelId","payload"],"properties":{"key":{"type":"string"},"guildId":{"type":"string"},"channelId":{"type":"string"},"payload":{"$ref":"#/components/schemas/V2Payload"}}},"Company":{"type":"object","additionalProperties":false,"required":["id","name"],"properties":{"id":{"type":"string","pattern":"^[a-z0-9][a-z0-9_-]{0,63}$"},"name":{"type":"string","minLength":2,"maxLength":80}}}}}
}`
