FROM liquibase/liquibase:4.31

WORKDIR /liquibase/changelog

COPY database ./database
COPY internal/messages/postgres/changelog.xml ./internal/messages/postgres/changelog.xml
COPY internal/messages/postgres/migrations ./internal/messages/postgres/migrations
COPY internal/performance/postgres/changelog.xml ./internal/performance/postgres/changelog.xml
COPY internal/performance/postgres/migrations ./internal/performance/postgres/migrations
